### ISSUE TITLE
Switch audio media status from 'beta' to 'supported'

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1315]
When audio is fully supported and out of beta, we should switch the MediaStatus to 'supported' to remove the beta button from the audio item in the content switcher.

## Milestone 

https://github.com/WordPress/openverse-frontend/milestone/16

## API-related issues

- [x] WordPress/openverse-api#615
- [x] WordPress/openverse-api#653
- [x] WordPress/openverse-api#528
- [x] WordPress/openverse-api#726

## Catalog-related issues
- [x] WordPress/openverse-catalog#558
- [x] WordPress/openverse-catalog#263
- [x] WordPress/openverse-catalog#658

## Others (Not blocking the milestone)

- [ ] ~WordPress/openverse#142~ 
- [ ] ~WordPress/openverse-api#716~

**Comment by zackkrida** [comment]
Hmm, as far as deployment is concerned should this be feature-flagged instead of hardcoded?

**Comment by krysal** [comment]
I'm fine with either way, could be feature-flagged to release it quickly though maybe it will simplify code if we removed it completely (?)
