### ISSUE TITLE
[Meta] i18n support

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#143]
## Problem

There are several steps we need to take to prepare the repository for translation into the 16 languages for launch. This issue will track the progress on all of them.

- [ ] #155

- [x] #151 
Add scripts to convert `json` translation files into `.po` files, and vice versa. 
- [ ] #112 
- [ ] Make sure that styles work well with right-to-left languages, such as Arabic and Hebrew.
- [ ] Create pluralization rules for any of the 16 languages

## The first 16 languages
Arabic, Brazilian Portuguese, Chinese (China), Chinese (Taiwan), Dutch, French, German, Hebrew, Indonesian, Italian, Japanese, Korean, Spanish, Swedish, Russian, Turkish

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Thank you for aggregating this work!
