### ISSUE TITLE
Add E2E and VRT tests for new header and footer

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1843]
## Problem
The new header and footer are being developed behind a feature flag which makes it harder to write E2E and VRT test cases for them. This is being addressed in #1837.

## Description

Once #1837 is resolved, tests need to be added for the following components.

- [x] `VHeaderInternal` - Storybook VR tests added in #1825
- [x] `VHeaderContent` - Playwright VR tests added in #1968
- [x] `VFooter` - Storybook VR tests added in #1969
- [x] `VSelectField` - Storybook VR tests added in #1821
- [x] `VLanguageSelect` - Storybook VR tests added in #1821

## Alternatives

Snapshot testing for components (not pages) should be done from Storybook wherever feasible. This would enable us to snapshot all the different states of a component and see them in isolation, independently of the other stuff on the page. Hopefully, it will also make the snaps more resilient to small shifts and make it easier to pinpoint the change if the snapshots do not line up.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
This issue should also include the work on updating the existing tests to pass with the `new_header` enabled.
