### ISSUE TITLE
[Feature] Clean up filterbar appearance in transitional styles

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#227]
The current filterbar is particularly unpleasant with odd font sizes. As this is such a commonly-used feature, we should clean it up a bit to better reflect the mockup.

## Mockup

- Figma: https://www.figma.com/file/Eaed5TMmqTrscI6WbjeJxP/Transitional-styles-(Copy)?node-id=0%3A1

![image](https://user-images.githubusercontent.com/6351754/133525044-eb682ca6-f55c-409e-8245-2667ecd14c50.png)

## Current appearance

<img width="358" alt="CleanShot 2021-09-15 at 19 21 11@2x" src="https://user-images.githubusercontent.com/6351754/133525573-6fb24f2e-aaaa-49af-8b47-8841b8236142.png">

## Tasks

- [ ] Filter heading size
- [ ] Filter heading spacing
- [ ] " Filter results by " and "hide filters" should be vertically centered
- [ ] Remove horizontal dividers between filters
- [ ] New sidebar icon (use SVGs please)
- [ ] Increase checkbox size
	- optional and related: #222 
- [ ] Related: #226

## Sizes

<img width="264" alt="CleanShot 2021-09-15 at 19 04 46@2x" src="https://user-images.githubusercontent.com/6351754/133524973-658ad661-d155-4766-a274-2d9f3c3813aa.png">
<img width="372" alt="CleanShot 2021-09-15 at 19 04 39@2x" src="https://user-images.githubusercontent.com/6351754/133524978-e76aaaf6-cd3b-40f9-8d2a-b70af61afec4.png">

Additionally, the filter headings should be:

```
font-size: 1rem;
font-weight: 600;
```

**Comment by DillonKyleDev** [comment]
Hi!
I'm new to contributing to open source and want to help.  Forgive the silly question but how do I find the specific scss file for the filter bar?
Thank you!

**Comment by zackkrida** [comment]
Hi @DillonKyleDev I think you'll have to use a bit of trial and error. The Filter sidebar uses some global styles as well as styles within the component.

This is the main Vue file for the filters, and might be a good place for you to start exploring:

https://github.com/WordPress/openverse-frontend/blob/db693f08f2046c24808addf9f2636352d010e062/src/components/Filters/FiltersList.vue

**Comment by DillonKyleDev** [comment]
@zackkrida you are so right, I'll figure it out! Thanks for the nudge in the right direction :)

**Comment by zackkrida** [comment]
@DillonKyleDev have fun 😄 If you need help, we also have a [slack channel](https://wordpress.slack.com/messages/openverse/) that you'll be able to view after signing up [here](https://make.wordpress.org/chat/).

**Comment by DillonKyleDev** [comment]
Good morning!
I was wondering if you could somehow give me access to the figma links that are posted in both this issue and in the issue linked in task number 7?  For some reason I'm not able to view either of them, but I'm not familiar with figma.

Also I was curious about the task:
>New sidebar icon (use SVGs please)

Which icon needs replacing?

Thanks for your patience!
