### ISSUE TITLE
[Meta] Audio

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#61]
A long awaited feature for Openverse is support for Audio files. We currently have some [limited audio support through meta search](https://search.creativecommons.org/search/audio?q=beep), but would like to expand this to first-class support for audio files. This issue is meant to track progress on Audio across all three repositories; sub-issues within each repo can and _should_ be made. Feel free to edit this post to link them.

## Supporting documents

- Francisco's original [audio mockups](https://www.figma.com/file/uLYzZQERl22CCT7vmnKNOY/Mockup-S6-Audio-integration)

### [Frontend](https://github.com/wordpress/openverse-frontend)

- [ ] Search results page defaults to an 'all media types' view (see below example:)
<img width="838" alt="CleanShot 2021-05-10 at 20 44 44@2x" src="https://user-images.githubusercontent.com/6351754/117741476-97060480-b1d0-11eb-91d6-ef08c7fc893b.png">

- [ ] Audio results no longer shows meta search; instead shows audio results
- [ ] Conditional filters in the sidebar when audio results are present: 
	- Genre
	- Duration
	- Format (filetype)
- [ ] New frontend components
    - [ ] Audio track list view
        - [ ] waveform
        - [ ] play/pause button
        - [ ] license icons
        - [ ] duration
        - [ ] album art
    - [ ] Single audio result view
        - [ ] 'similar audio' and 'more from the same creator' sections
        - [ ] download buttons
        - [ ] metadata tables

### [API](https://github.com/wordpress/openverse-api)

- [ ] New endpoints for audio
- [ ] Make the thumbnail server work with audio album art/images

### [Catalog](https://github.com/wordpress/openverse-catalog)

- [ ] New audio DB table
  - [ ] Columns for common metatdata
  - [ ] JSON column to dump arbitrary, unique, extra metadata
- [ ] New models for a catalog entity, with subclasses for image, audio, etc.
- [ ] New DAGs for each audio provider
