### ISSUE TITLE
Single audio result view cleanup

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#740]
## Description

The single audio result view needs some cleanup:

|Live|Mockup|
|-|-|
|![CleanShot 2022-01-27 at 14 15 24@2x](https://user-images.githubusercontent.com/6351754/151428750-7d52c79e-2789-44c4-a0bf-83f8571dd405.png)|![image](https://user-images.githubusercontent.com/6351754/151428925-3ba758f0-eec3-4591-be03-b18ad2d5481c.png)|

## Todos

- [ ] Increase waveform height
- [ ] New tag style
- [ ] Hide provider in details section
- [ ] Should link to the source
- [ ] Remove pluralization from 'Related audios'
- [ ] Switch related audio layout

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.
